version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engin_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - engin_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: engin_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: engin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - engin_network

networks:
  engin_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
